responsive home page
Pradumnasaraf/Pradumnasaraf.github.io pull request #21
Opened 2022-10-12 20:41 UTC by E-fais

## 🛠️ Fixes Issue

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-10-12 20:42 UTC, E-fais commented
Fix issue #21

2022-10-14 17:37 UTC, Pradumnasaraf requested changes
Hey, thank you for the PR. I think we don't need the js file. Otherwise Looks good.

2022-10-14 17:37 UTC, Pradumnasaraf commented on index.html
> +    <script src="main.js"></script>
```suggestion

```

2022-10-15 04:53 UTC, E-fais commented on index.html
> +    <script src="main.js"></script>
Yes ;)

2022-10-15 04:58 UTC, E-fais commented
Done ✔️

2022-10-15 17:54 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-15 17:55 UTC, merged

2022-10-15 19:37 UTC, E-fais commented
Thanks for accepting my PR .